### ISSUE TITLE
Modifiable Services false positives for explicit AccessDenied DACLs 

### ISSUE THREAD

**Issue by e0x70i** [GhostPack/SharpUp#12]
Noticed false positives for a number of services, for example most McAfee services. 

![image](https://user-images.githubusercontent.com/18584157/44875767-636f3000-ac5c-11e8-92e0-bad000754729.png)

Checked the ACL and it turns out they have an explicit access denied for the authenticated users SID. 

This can probably be fixed by checking the ACE type. 

Some jank debug shows the access control type is "AccessDenied" for the false positive sid.  
 ```
Console.WriteLine("DACL for SID: " + ace.SecurityIdentifier);
                                Console.WriteLine(ace.AccessMask);
                                Console.WriteLine(ace.AceType);
```

![image](https://user-images.githubusercontent.com/18584157/44875857-9285a180-ac5c-11e8-88fc-4d56d8c86207.png)

Ace types: https://docs.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.acetype?view=netframework-4.7.2

**Comment by cnotin** [comment]
See #15 ;)
